name: "update-calendar"
on:
  schedule:
  - cron: "0 4 * * *"
  
  push:
    branches:
      - main

jobs:
  update-calendar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2

      - name: Download calendar
        run: wget -O cal.ics ${{ secrets.CALENDAR_URL }}

      - name: Setup identity
        run: |
          git config --global user.email "bot@example.com"
          git config --global user.name "Github Actions"
          
      - name: Commit if the calendar changes
        run: (test -n "$(git diff)" && git add cal.ics && git commit -m 'update-calendar') || true
          
      - name: Push changes
        run: git push -f
